### PR TITLE
feat: Integrate stripe

### PR DESCRIPTION
**Pull request by pointearth**
## Description
#1186 
Add camel/toolkits/stripe_toolkit.py
## Motivation and Context

- [ ] Add stripe toolkit
- [ ] Need to be checked if the solution fit expected design

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] New feature (stripe support, including some read-only functions as the first step)
- [ ] Documentation (update in the documentation)
- [ ] Unit Tests

## Implemented Tasks

- [x] CustomerAdapter (get_customer, list_customers)
- [x] BalanceAdapter (get_balance,list_balance_transactions)
- [x] PaymentAdapter (get_payment, list_payments)
- [x] RefundAdapter (get_refund, list_refunds)
- [x] Aggregate functions into the class StripeToolkit
- [x] Provide a base class StripeBaseAdapter to wrap base functions for Adapters
- [x] .env
- [x] pyproject.toml

## Checklist
- [x] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by NeilJohnson0930** [comment]
Great work on the code so far! Have you considered adding a verification step for conversations between humans and agents to ensure security when using the transaction function?

**Comment by pointearth** [comment]
aaa test coment

**Review by Wendong-Fan — COMMENTED** [review]
Thanks @pointearth  and sorry for the late review, left some comments below and added one more commit here based on the comment, please feel free to review the change, currently there's one error `error: Module "stripe.error" has no attribute "StripeError"`, which also lead the unit test not passing, could you help check this part further? Thanks!

**Review by Wendong-Fan — APPROVED** [review]
Thanks @pointearth ! LGTM

**Pull request merged**
