### PR TITLE
Make markdown tutorials for `BaseMessage`

### PR DESCRIPTION
**Pull request by tczhangzhi**
## Description

Describe your changes in detail.

## Motivation and Context

Why is this change required? What problem does it solve?
#132 

- [ ] I have raised an issue to propose this change ([required](https://github.com/camel-ai/camel/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)
- [ ] Example (update in the folder of example)

## Implemented Tasks

- [ ] Subtask 1
- [x] Subtask 2
- [ ] Subtask 3

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [x] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tczhangzhi** [comment]
Objective: Create a tutorial about the {BaseMessage} class, including examples based on source code and unit test cases.

Prompts:
* Source Code: Examine the source code of the {BaseMessage} class and its unit test cases to understand its implementation and functionality.
* Introduction: Write an introduction to the {BaseMessage} class, explaining its purpose.
* Creating a {BaseMessage} instance: Explain how to create a {BaseMessage} instance.
* Describe the properties of the {BaseMessage} class and provide an example of using them.
* Explain the method of the {BaseMessage} class and provide an example of using them.
* Conclusion: Summarize the key points of the tutorial and encourage readers to try using the {BaseMessage} class in their projects.


Source Code:
```python
class BaseMessage:
    r"""Base class for message objects used in CAMEL chat system.

    Args:
        role_name (str): The name of the user or assistant role.
        role_type (RoleType): The type of role, either
            :obj:`RoleType.ASSISTANT` or :obj:`RoleType.USER`.
        meta_dict (Optional[Dict[str, str]]): Additional metadata dictionary
            for the message.
        role (str): The role of the message in OpenAI chat system, either
            :obj:`"system"`, :obj:`"user"`, or :obj:`"assistant"`.
        content (str): The content of the message.
    """
    role_name: str
    role_type: RoleType
    meta_dict: Optional[Dict[str, str]]
    role: str
    content: str

    def to_user_chat_message(self) -> "UserChatMessage":
        r"""Converts the message to a :obj:`UserChatMessage` object.

        Returns:
            UserChatMessage: The converted :obj:`UserChatMessage` object.
        """
        return UserChatMessage(
            role_name=self.role_name,
            role_type=self.role_type,
            meta_dict=self.meta_dict,
            content=self.content,
        )

    def to_assistant_chat_message(self) -> "AssistantChatMessage":
        r"""Converts the message to an :obj:`AssistantChatMessage` object.

        Returns:
            AssistantChatMessage: The converted :obj:`AssistantChatMessage`
                object.
        """
        return AssistantChatMessage(
            role_name=self.role_name,
            role_type=self.role_type,
            meta_dict=self.meta_dict,
            content=self.content,
        )

    def to_openai_message(self, role: Optional[str] = None) -> OpenAIMessage:
        r"""Converts the message to an :obj:`OpenAIMessage` object.

        Args:
            role (Optional[str]): The role of the message in OpenAI chat
                system, either :obj:`"system"`, :obj:`"user"`, or
                obj:`"assistant"`. (default: :obj:`None`)

        Returns:
            OpenAIMessage: The converted :obj:`OpenAIMessage` object.
        """
        role = role or self.role
        if role not in {"system", "user", "assistant"}:
            raise ValueError(f"Unrecognized role: {role}")
        return {"role": role, "content": self.content}

    def to_openai_chat_message(
        self,
        role: Optional[str] = None,
    ) -> OpenAIChatMessage:
        r"""Converts the message to an :obj:`OpenAIChatMessage` object.

        Args:
            role (Optional[str]): The role of the message in OpenAI chat
                system, either :obj:`"user"`, or :obj:`"assistant"`.
                (default: :obj:`None`)

        Returns:
            OpenAIChatMessage: The converted :obj:`OpenAIChatMessage` object.
        """
        role = role or self.role
        if role not in {"user", "assistant"}:
            raise ValueError(f"Unrecognized role: {role}")
        return {"role": role, "content": self.content}

    def to_openai_system_message(self) -> OpenAISystemMessage:
        r"""Converts the message to an :obj:`OpenAISystemMessage` object.

        Returns:
            OpenAISystemMessage: The converted :obj:`OpenAISystemMessage`
                object.
        """
        return {"role": "system", "content": self.content}

    def to_openai_user_message(self) -> OpenAIUserMessage:
        r"""Converts the message to an :obj:`OpenAIUserMessage` object.

        Returns:
            OpenAIUserMessage: The converted :obj:`OpenAIUserMessage` object.
        """
        return {"role": "user", "content": self.content}

    def to_openai_assistant_message(self) -> OpenAIAssistantMessage:
        r"""Converts the message to an :obj:`OpenAIAssistantMessage` object.

        Returns:
            OpenAIAssistantMessage: The converted :obj:`OpenAIAssistantMessage`
                object.
        """
        return {"role": "assistant", "content": self.content}

    def to_dict(self) -> Dict:
        r"""Converts the message to a dictionary.

        Returns:
            dict: The converted dictionary.
        """
        return {
            "role_name": self.role_name,
            "role_type": self.role_type.name,
            **(self.meta_dict or {}),
            "role": self.role,
            "content": self.content,
        }
```

Unit Test Cases:
```python
def base_message() -> BaseMessage:
    return BaseMessage(
        role_name="test_user",
        role_type=RoleType.USER,
        meta_dict={"key": "value"},
        role="user",
        content="test content",
    )
```

Based on these prompts, source code, and unit test cases, create a comprehensive tutorial that explains the {BaseMessage} class and provides examples of its usage.

**Comment by tczhangzhi** [comment]
Add a session  to introduce its subclasses `SystemMessage`, `AssistantSystemMessage`, `UserSystemMessage`, `ChatMessage`, `AssistantChatMessage`, and `UserChatMessage`, and some default properties are pre-defined in these subclasses.

```python
@dataclass
class SystemMessage(BaseMessage):
    r"""Class for system messages used in CAMEL chat system.

    Args:
        role_name (str): The name of the user or assistant role.
        role_type (RoleType): The type of role, either
            :obj:`RoleType.ASSISTANT` or :obj:`RoleType.USER`.
        meta_dict (Optional[Dict[str, str]]): Additional metadata dictionary
            for the message.
        role (str): The role of the message in OpenAI chat system.
            (default: :obj:`"system"`)
        content (str): The content of the message. (default: :obj:`""`)
    """
    role_name: str
    role_type: RoleType
    meta_dict: Optional[Dict[str, str]] = None
    role: str = "system"
    content: str = ""


@dataclass
class AssistantSystemMessage(SystemMessage):
    r"""Class for system messages from the assistant used in the CAMEL chat
    system.

    Args:
        role_name (str): The name of the assistant role.
        role_type (RoleType): The type of role, always
            :obj:`RoleType.ASSISTANT`.
        meta_dict (Optional[Dict[str, str]]): Additional metadata dictionary
            for the message.
        role (str): The role of the message in OpenAI chat system.
            (default: :obj:`"system"`)
        content (str): The content of the message. (default: :obj:`""`)
    """
    role_name: str
    role_type: RoleType = RoleType.ASSISTANT
    meta_dict: Optional[Dict[str, str]] = None
    role: str = "system"
    content: str = ""


@dataclass
class UserSystemMessage(SystemMessage):
    r"""Class for system messages from the user used in the CAMEL chat system.

    Args:
        role_name (str): The name of the user role.
        role_type (RoleType): The type of role, always :obj:`RoleType.USER`.
        meta_dict (Optional[Dict[str, str]]): Additional metadata dictionary
            for the message.
        role (str): The role of the message in OpenAI chat system.
            (default: :obj:`"system"`)
        content (str): The content of the message. (default: :obj:`""`)
    """
    role_name: str
    role_type: RoleType = RoleType.USER
    meta_dict: Optional[Dict[str, str]] = None
    role: str = "system"
    content: str = ""


@dataclass
class ChatMessage(BaseMessage):
    r"""Base class for chat messages used in CAMEL chat system.

    Args:
        role_name (str): The name of the user or assistant role.
        role_type (RoleType): The type of role, either
            :obj:`RoleType.ASSISTANT` or :obj:`RoleType.USER`.
        meta_dict (Optional[Dict[str, str]]): Additional metadata dictionary
            for the message.
        role (str): The role of the message in OpenAI chat system.
        content (str): The content of the message. (default: :obj:`""`)
    """
    role_name: str
    role_type: RoleType
    meta_dict: Optional[Dict[str, str]]
    role: str
    content: str = ""


@dataclass
class AssistantChatMessage(ChatMessage):
    r"""Class for chat messages from the assistant role used in CAMEL chat
    system.

    Args:
        role_name (str): The name of the assistant role.
        role_type (RoleType): The type of role, always
            :obj:`RoleType.ASSISTANT`.
        meta_dict (Optional[Dict[str, str]]): Additional metadata dictionary
            for the message.
        role (str): The role of the message in OpenAI chat system.
            (default: :obj:`"assistant"`)
        content (str): The content of the message. (default: :obj:`""`)
    """
    role_name: str
    role_type: RoleType = RoleType.ASSISTANT
    meta_dict: Optional[Dict[str, str]] = None
    role: str = "assistant"
    content: str = ""


@dataclass
class UserChatMessage(ChatMessage):
    r"""Class for chat messages from the user role used in CAMEL chat system.

    Args:
        role_name (str): The name of the user role.
        role_type (RoleType): The type of role, always :obj:`RoleType.USER`.
        meta_dict (Optional[Dict[str, str]]): Additional metadata dictionary
            for the message.
        role (str): The role of the message in OpenAI chat system.
            (default: :obj:`"user"`)
        content (str): The content of the message. (default: :obj:`""`)
    """
    role_name: str
    role_type: RoleType = RoleType.USER
    meta_dict: Optional[Dict[str, str]] = None
    role: str = "user"
    content: str = ""


MessageType = Union[BaseMessage, SystemMessage, AssistantSystemMessage,
                    UserSystemMessage, ChatMessage, AssistantChatMessage,
                    UserChatMessage]
SystemMessageType = Union[SystemMessage, AssistantSystemMessage,
                          UserSystemMessage]
ChatMessageType = Union[ChatMessage, AssistantChatMessage, UserChatMessage]
```

**Comment by tczhangzhi** [comment]
Based on all the test cases and codes mentioned above, optimize the following tutorial documents again:

Supplemented unit test cases:
```python
def test_base_message():
    role_name = "test_role_name"
    role_type = RoleType.USER
    meta_dict = {"key": "value"}
    role = "user"
    content = "test_content"

    message = BaseMessage(role_name=role_name, role_type=role_type,
                          meta_dict=meta_dict, role=role, content=content)

    assert message.role_name == role_name
    assert message.role_type == role_type
    assert message.meta_dict == meta_dict
    assert message.role == role
    assert message.content == content

    user_message = message.to_user_chat_message()
    assert user_message.role_name == role_name
    assert user_message.role_type == role_type
    assert user_message.meta_dict == meta_dict
    assert user_message.role == "user"
    assert user_message.content == content

    assistant_message = message.to_assistant_chat_message()
    assert assistant_message.role_name == role_name
    assert assistant_message.role_type == role_type
    assert assistant_message.meta_dict == meta_dict
    assert assistant_message.role == "assistant"
    assert assistant_message.content == content

    openai_message = message.to_openai_message()
    assert openai_message == {"role": role, "content": content}

    openai_chat_message = message.to_openai_chat_message()
    assert openai_chat_message == {"role": role, "content": content}

    openai_system_message = message.to_openai_system_message()
    assert openai_system_message == {"role": "system", "content": content}

    openai_user_message = message.to_openai_user_message()
    assert openai_user_message == {"role": "user", "content": content}

    openai_assistant_message = message.to_openai_assistant_message()
    assert openai_assistant_message == {
        "role": "assistant",
        "content": content
    }

    dictionary = message.to_dict()
    assert dictionary == {
        "role_name": role_name,
        "role_type": role_type.name,
        **(meta_dict or {}), "role": role,
        "content": content
    }


def test_system_message():
    role_name = "test_role_name"
    role_type = RoleType.USER
    meta_dict = {"key": "value"}
    content = "test_content"

    message = SystemMessage(role_name=role_name, role_type=role_type,
                            meta_dict=meta_dict, content=content)

    assert message.role_name == role_name
    assert message.role_type == role_type
    assert message.meta_dict == meta_dict
    assert message.role == "system"
    assert message.content == content

    dictionary = message.to_dict()
    assert dictionary == {
        "role_name": role_name,
        "role_type": role_type.name,
        **(meta_dict or {}), "role": "system",
        "content": content
    }


def test_base_message_to_dict(base_message: BaseMessage) -> None:
    expected_dict = {
        "role_name": "test_user",
        "role_type": "USER",
        "key": "value",
        "role": "user",
        "content": "test content",
    }
    assert base_message.to_dict() == expected_dict


def test_system_message_to_dict(system_message: SystemMessage) -> None:
    expected_dict = {
        "role_name": "test_assistant",
        "role_type": "ASSISTANT",
        "role": "system",
        "content": "test system message",
    }
    assert system_message.to_dict() == expected_dict

```

the current tutorial document to be optimized:

```markdown
# Tutorial: Working with the `BaseMessage` Class

In this tutorial, we will explore the `BaseMessage`, `SystemMessage`, `AssistantSystemMessage`, `UserSystemMessage`, `ChatMessage`, `AssistantChatMessage`, and `UserChatMessage` class. The topics covered include:

1. Introduction to the `BaseMessage` class
2. Creating a `BaseMessage` instance
3. Understanding the properties of the `BaseMessage` class
4. Using the methods of the `BaseMessage` class`BaseMessage`
5. Subclasses of `BaseMessage`

## Introduction

The `BaseMessage` class is the base class for message objects used in the CAMEL chat system. It is designed to provide a consistent structure for the messages in the system and allow for easy conversion between different message types.

## Creating a `BaseMessage` Instance

To create a `BaseMessage` instance, you need to provide the following arguments:

- `role_name`: The name of the user or assistant role.
- `role_type`: The type of role, either `RoleType.ASSISTANT` or `RoleType.USER`.
- `meta_dict`: An optional metadata dictionary for the message.
- `role`: The role of the message in the OpenAI chat system, either `"system"`, `"user"`, or `"assistant"`.
- `content`: The content of the message.

Here's an example of creating a `BaseMessage` instance:

```python
from camel.messages import BaseMessage, RoleType

message = BaseMessage(
    role_name="test_user",
    role_type=RoleType.USER,
    meta_dict={"key": "value"},
    role="user",
    content="test content"
)
```

## Understanding the Properties of the BaseMessage Class

The `BaseMessage` class has the following properties:

- `role_name`: A string representing the name of the user or assistant role.
- `role_type`: An instance of the `RoleType` enumeration, indicating whether the role is a user or an assistant.
- `meta_dict`: A dictionary containing additional metadata for the message.
- `role`: A string representing the role of the message in the OpenAI chat system.
- `content`: A string containing the content of the message.

In the example provided earlier, the `role_name` is `"test_user"`, the `role_type` is `RoleType.USER`, the `meta_dict` is `{"key": "value"}`, the `role` is `"user"`, and the `content` is `"test content"`.

## Using the Methods of the `BaseMessage` Class

The `BaseMessage` class provides methods for converting the message to different message types, such as `UserChatMessage`, `AssistantChatMessage`, and various OpenAI message types. Here are some examples:

1. Converting to a `UserChatMessage` object:

```python
from camel.messages import UserChatMessage

user_chat_message = message.to_user_chat_message()
assert isinstance(user_chat_message, UserChatMessage)
```

2. Converting to an `AssistantChatMessage` object:

```python
from camel.messages import AssistantChatMessage

assistant_chat_message = message.to_assistant_chat_message()
assert isinstance(assistant_chat_message, AssistantChatMessage)
```

3. Converting to an `OpenAIMessage` object:

```python
openai_message = message.to_openai_message()
assert openai_message == {"role": "user", "content": "test content"}
```

4. Converting to a dictionary:

```python
message_dict = message.to_dict()
assert message_dict == {
    "role_name": "test_user",
    "role_type": "USER",
    "key": "value",
    "role": "user",
    "content": "test content"
}
```

These methods allow you to convert a `BaseMessage` instance into different message types depending on your needs.

## Subclasses of `BaseMessage`

In this session, we will introduce the subclasses of the `BaseMessage` class. Each of these subclasses has some default properties pre-defined, making it convenient to create message instances of specific types.

* `SystemMessage` is a class for system messages used in the CAMEL chat system. By default, the `role` is set to `"system"` and the `content` is an empty string `""`

* `AssistantSystemMessage` is a class for system messages from the assistant role used in the CAMEL chat system. By default, the `role_type` is set to `RoleType.ASSISTANT`, the `role` is set to `"system"`, and the `content` is an empty string `""`.

* `UserSystemMessage` is a class for system messages from the user role used in the CAMEL chat system. By default, the `role_type` is set to `RoleType.USER`, the `role` is set to `"system"`, and the `content` is an empty string `""`.

* `ChatMessage` is a base class for chat messages used in the CAMEL chat system. By default, the `content` is an empty string `""`.

* `AssistantChatMessage` is a class for chat messages from the assistant role used in the CAMEL chat system. By default, the `role_type` is set to `RoleType.ASSISTANT`, the `role` is set to `"assistant"`, and the `content` is an empty string `""`.

* `UserChatMessage` is a class for chat messages from the user role used in the CAMEL chat system. By default, the `role_type` is set to `RoleType.USER`, the `role` is set to `"user"`, and the `content` is an empty string `""`.

These subclasses allow you to create message instances with specific roles and types easily. You can use them to create, manage, and manipulate messages in the CAMEL chat system with more context and clarity.
```

**Comment by lightaime** [comment]
Thanks for the first PR @tczhangzhi! I will merge this PR for now but will rework it later since the `messages.py` has been refactored.

**Review by lightaime — APPROVED** [review]

**Pull request merged**
