### PR TITLE
docs: add Camel docs - prompt

### LINKED ISSUE #774: [Feature Request] Documentation for `Prompt`
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Documentation for `Prompt`

### Solution

_No response_

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lllllyh01**
## Description

Add Camel docs: prompt

## Motivation and Context

close #774

- [ ] I have raised an issue to propose this change ([required](https://github.com/camel-ai/camel/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)
- [ ] Example (update in the folder of example)

## Implemented Tasks

- [ ] Subtask 1
- [ ] Subtask 2
- [ ] Subtask 3

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by Wendong-Fan — APPROVED** [review]
Thanks @lllllyh01  !
I added one commit here https://github.com/camel-ai/camel/pull/840/commits/76869ea6475087aa705659d8a3d4151b6e6d6364

Mainly enhanced the format to make the style more uniformed with other docs

**Review by CaelumF — APPROVED** [review]
Hi, I've tried the code and it looks good. I committed some minor grammar and phrasing changes directly to avoid PR overhead, please have a look and revert those changes if I've messed anything up 😄

**Comment by lllllyh01** [comment]
> Thanks @lllllyh01 ! I added one commit here [76869ea](https://github.com/camel-ai/camel/commit/76869ea6475087aa705659d8a3d4151b6e6d6364)
> 
> Mainly enhanced the format to make the style more uniformed with other docs

Sorry for the late reply, I missed this message. It looks much better, thank you Wendong!

**Comment by lllllyh01** [comment]
> Hi, I've tried the code and it looks good. I committed some minor grammar and phrasing changes directly to avoid PR overhead, please have a look and revert those changes if I've messed anything up 😄

Thank you Caelum! Everything looks good to me

**Pull request merged**
