### PR TITLE
docs: add member PR instruction

### PR DESCRIPTION
**Pull request by lightaime**
## Description

The `fork-and-pull-request` workflow can not pass tests with GitHub secretes. It is recommended to follow `checkout-and-pull-request` workflow for organization members.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)
- [ ] Example (update in the folder of example)

### CODE REVIEW

**Comment by dandansamax** [comment]
Thank you for this important update! However, I didn't get the idea of "Checkout-and-Pull-Request". The given blog seems to describe the same thing as "Fork-and-Pull-Request".

**Comment by Benjamin-eecs** [comment]
> Thank you for this important update! However, I didn't get the idea of "Checkout-and-Pull-Request". The given blog seems to describe the same thing as "Fork-and-Pull-Request".

"Checkout-and-Pull-Request" is to let member clone the repo and checkout a new branch and open up a pr with this new branch instead of cloning first.

**Comment by dandansamax** [comment]
> "Checkout-and-Pull-Request" is to let member clone the repo and checkout a new branch and open up a pr with this new branch instead of forking first.

Thanks for explanation. But the given blog still contains forking process. Confusing me.

**Comment by lightaime** [comment]
> > "Checkout-and-Pull-Request" is to let member clone the repo and checkout a new branch and open up a pr with this new branch instead of forking first.
> 
> Thanks for explanation. But the given blog still contains forking process. Confusing me.

Thanks for spotting it. Sorry that I got a wrong like. Updated to another one.

**Review by dandansamax — APPROVED** [review]
LGTM! Thanks.

**Review by Obs01ete — COMMENTED** [review]
Is there a way for a non-team-member to trigger our CI?

**Comment by lightaime** [comment]
> Is there a way for a non-team-member to trigger our CI? @lightaime If there is not way, I am good with the PR.

I am not aware of this.

**Pull request merged**
