### PR TITLE
feat: add docker support of code execution

### LINKED ISSUE #623: [Feature Request] Integrate Docker
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

docker can be used to create split environment for more safe code execute.
Install camel with docker.

### Solution

_No response_

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by WHALEEYE**
## Description

Added docker container support for the current code executor

## Motivation and Context

partly closed #623 

- [ ] I have raised an issue to propose this change ([required](https://github.com/camel-ai/camel/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [ ] Example (update in the folder of example)

## Implemented Tasks

- [ ] Subtask 1
- [ ] Subtask 2
- [ ] Subtask 3

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by onemquan — COMMENTED** [review]
LGTM overall, while there are some details need to fix.

**Comment by WHALEEYE** [comment]
Hi @onemquan, thx for your review and I think these points are good and should be fixed if we are going to make code execution as tools. Although, my opinion is maybe we can move most of the fixes (except the one that detects if docker is present in the host system, because I'm also going to fix this in the tests soon) into a new PR. I said this mainly out of the reason that the docker interpreter in this PR basically just adds container support into the `subprocessInterpreter` that we already have, and this interpreter also has these problems you mentioned. Therefore, I think it's better to raise a new PR to do a thorough refactor of the interpreters we have right now to fit it into the tools.

**Review by onemquan — APPROVED** [review]
Let's create a new PR for the comments.

**Review by Wendong-Fan — COMMENTED** [review]
Thanks @WHALEEYE ! Left some comments, overall LGTM, could you please also add example code

**Review by Wendong-Fan — APPROVED** [review]

**Pull request merged**
