### PR TITLE
docs: Update installation instructions

### PR DESCRIPTION
**Pull request by tom-doerr**
## Description

I added the `--no-cache` option to the poetry commands.

## Motivation and Context

Both poetry commands didn't work for me without adding the `--no-cache` option.
If someone really wants to use the cache it's obvious that they just have to omit the flag. 

- [ ] I have raised an issue to propose this change ([required](https://github.com/camel-ai/camel/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)
- [ ] Example (update in the folder of example)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by Wendong-Fan — COMMENTED** [review]
Thanks @tom-doerr  for the PR! I appreciate the thought behind using poetry install --no-cache, especially when there's a concern about outdated or corrupted packages. However, I believe that using `poetry install` without the `--no-cache` flag is more standard and aligns better with typical workflows.

The standard poetry install is designed to leverage cached packages, which speeds up installation and reduces redundant downloads. This is particularly useful for maintaining efficiency across multiple environments or projects. 

How about we add  content like
`# if you want to ensure the latest package versions or resolving a cache-related problem`
`poetry install --no-cache`
instead of making `--no-cache` as default installing mode?

**Comment by tom-doerr** [comment]
I suspect the underlying issue is that the range of accepted package versions is too wide, maybe those should be adapted. 
For the time being, here's the note I added:
image

What do you think?

**Comment by Wendong-Fan** [comment]
> I suspect the underlying issue is that the range of accepted package versions is too wide, maybe those should be adapted. For the time being, here's the note I added: image
> 
> What do you think?

Thanks @tom-doerr for the insight and contribution, the tip format looks great!

**Review by Wendong-Fan — APPROVED** [review]

**Comment by tom-doerr** [comment]
Just to have it documented somewhere, those are the errors I get when not using the cache flag:
```
  'HTTPResponse' object has no attribute 'strict'

  at ~/.local/lib/python3.10/site-packages/cachecontrol/serialize.py:54 in dumps
       50│                 ),
       51│                 u"status": response.status,
       52│                 u"version": response.version,
       53│                 u"reason": text_type(response.reason),
    →  54│                 u"strict": response.strict,
       55│                 u"decode_content": response.decode_content,
       56│             }
       57│         }
       58│ 

  • Installing sphinxcontrib-qthelp (2.0.0): Failed

  AttributeError

  'HTTPResponse' object has no attribute 'strict'

  at ~/.local/lib/python3.10/site-packages/cachecontrol/serialize.py:54 in dumps
       50│                 ),
       51│                 u"status": response.status,
       52│                 u"version": response.version,
       53│                 u"reason": text_type(response.reason),
    →  54│                 u"strict": response.strict,
       55│                 u"decode_content": response.decode_content,
       56│             }
       57│         }
       58│ 

  • Installing sphinxcontrib-serializinghtml (2.0.0): Failed

  AttributeError

  'HTTPResponse' object has no attribute 'strict'

  at ~/.local/lib/python3.10/site-packages/cachecontrol/serialize.py:54 in dumps
       50│                 ),
       51│                 u"status": response.status,
       52│                 u"version": response.version,
       53│                 u"reason": text_type(response.reason),
    →  54│                 u"strict": response.strict,
       55│                 u"decode_content": response.decode_content,
       56│             }
       57│         }
       58│ 

```
The issue seems to appear with versions of `urllib3` >= 2.0 :https://github.com/python-poetry/poetry/issues/7936

**Pull request merged**
