### PR TITLE
feat: memory support

### PR DESCRIPTION
**Pull request by Benjamin-eecs**
## Description

Memory design in camel:
- memory storage
- memory types:
	- short-term
	- long-term

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [ ] Example (update in the folder of example)

## Checklist

- [ ] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dandansamax** [comment]
[](https://mermaid.live/edit#pako:eNqNVWFr2zAQ_SvCn7yt_gMmFNZlsI6WsgX2pS5BtS6OQJaCdNnIuvz3nS07tmRlzFAa7p7e3b27k96y2gjIyqwoikqjRAUle4TW2BNbg5ONrnTvqhV3bi15Y3lbkZHRp3kL7sBrYJ_bVxBC6oa9eVf39UfYHXeQdHffanWvEeyOOG5vQ9cH6A7lDrit92jfvWcP0uHzThmOLxP0PCYzRXw6gP4oLzEpZIUjotigZS2VrAKKgCnMePWnKGLKpQBesmTxg5pBGv-q2wIX-dMBpdFcPXsG53gDL6MGd45fbNHhX1Yi5B4VnIxwtSJd87n5HOf-A2o0dn13KW2mYsft_Rv6owjM-f9hmCKUEib9rkb9tOf4RXZsp1TgB-OcoqKuhl0QfofaNFr-hhRdWCNTRjdb6ku7baENgIu0mNsbizNwapoqXAplaJzCsKmpS6E82xC-H8sFgjCxQh3TIvsUWQqUgEV6dpBIRZNGLSVMA6PNGupYrNY3YbnG-EIpCG9LdrRqbN_Qjwp9OeFuhq357xVlNS0pwrY2ShEDbWq-2DDGhdgejNTo_D76WMtVZP6Ky71_3PEBHV108_zjRvfZe0CU-2imUPwn5GtZY5fFZKY7VVAFrPPMdAvj3evpJgslX1w3JVNkmjNhyPXVGT3LO9HBnVSwPXDcR308T9sSNq8fTj8UqTXo3WMJVwGzvCqd3WQtrTeXgt7HPssqwz20UGUl_RSw40eFVVbpM0H5Ec3mpOus3HHl4CY7HgTNyPBkXqwgJPE_-ke3f3vPfwGl-2kD)

This is current memory design. I will push the basic code without examples and documents by the end of tomorrow.

**Comment by Obs01ete** [comment]
Is it still a draft? Do you need a review?

**Comment by dandansamax** [comment]
> Is it still a draft? Do you need a review?

Yes, it’s still a draft. I will request review when I think it’s almost done.😁

**Comment by dandansamax** [comment]
Todo List:

- [ ] Vector DB
    - [x] Qdrant storage
    - [x] Qdrant test
    - [ ] VectorDBMemory
    - [ ] VectorDBTest
    - [ ] Document
    - [ ] Exmaples
- [ ] Chat History
    - [x] Chat History Memory & test
    - [x] Lossless storage & test 
        - [x] Json
        - [x] In-memory 
    - [ ] Document
    - [ ] Exmaples
- [ ] Cognitive Memory
    - [ ] Implement
    - [ ] Test
    - [ ] Document
    - [ ] Exmaples

**Comment by dandansamax** [comment]
Most of the core code is done. I will keep updating the documentation and examples.

**Comment by dandansamax** [comment]
This PR has too many contents, so I divide it into several parts. The first step is `ChatHistoryMemory` and agent memory interaction, see #280.

**Comment by Obs01ete** [comment]
Okay, I've got the idea where it all is going

**Comment by dandansamax** [comment]
This branch is the main branch for memory development. Close since it will not be merged.

**Pull request closed without merging**
