### PR TITLE
Add Code society to Agents

### PR DESCRIPTION
**Pull request by Obs01ete**
## Description

Switch layout between AI Society and Code in Agents App.

In actuality does not work well. If the language is set to C#, the chat progresses with Python. @lightaime 

## Motivation and Context

Solves #148.

## Types of changes

- [x] New feature (non-breaking change which adds core functionality)

### CODE REVIEW

**Comment by Obs01ete** [comment]
image

**Comment by lightaime** [comment]
The keywords in Code are different from keywords in AI society. I add an example here: https://github.com/camel-ai/camel/pull/211. We will need to pass extra `meta_dicts` through the `RolePlaying` API.

**Comment by Obs01ete** [comment]
> The keywords in Code are different from keywords in AI society. I add an example here: #211. We will need to pass extra `meta_dicts` through the `RolePlaying` API.

Thanks for the example. We definitely need to rework RolePlaying constructor since it is very unintuitive in its current implementation.

**Comment by Obs01ete** [comment]
image

**Review by lightaime — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
