### PR TITLE
Data i/o docstring format

### PR DESCRIPTION
**Pull request by Wendong-Fan**
## Description

quick fix of docstring format for data i/o functions

## Motivation and Context
-

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)
- [ ] Example (update in the folder of example)

## Implemented Tasks

-

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Wendong-Fan** [comment]
Hi @lightaime @Obs01ete  @dandansamax ,

I tried to fix the doc format but this PR can't pass the Pytest related to `role playing`, I only made changes to the doc so I don't understand how can I pass this error, do you have any ideas on this? Thank you~

Screenshot 2023-10-07 at 12 12 16

**Comment by dandansamax** [comment]
It seems that the failed test is merged in #302, committed by Zhiyu. Hi @zhiyu-01, could you please check the problem here?

**Comment by zhiyu-01** [comment]
The Pytest have passed now, but I also don't know why this happened.

**Review by Obs01ete — APPROVED** [review]
LGTM

**Comment by dandansamax** [comment]
Thank you so much for you contribution. Please feel free to merge it. We may not require everyone to approve this tiny fix. BTW, after we merge this pr, could you please create a new branch from the `main` branch for each new pr, as long as your older pr has been merged? This will make the commits history clearer.

**Comment by lightaime** [comment]
@Wendong-Fan thanks for the fix. It looks good. Please feel free to merge it!

**Comment by Wendong-Fan** [comment]
> Thank you so much for you contribution. Please feel free to merge it. We may not require everyone to approve this tiny fix. BTW, after we merge this pr, could you please create a new branch from the `main` branch for each new pr, as long as your older pr has been merged? This will make the commits history clearer.

Hi @dandansamax , thank you for the kind suggestion, will follow this

**Pull request merged**
