### PR TITLE
Fix `agent` `mypy` error

### PR DESCRIPTION
**Pull request by lightaime**
## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by lightaime** [comment]
@Obs01ete This PR also fix all the mypy error with nested agents. WDYT?

**Comment by Obs01ete** [comment]
Yeah, this fixes inheritance inconsistencies, that's fine, formally. However it kinda makes no sense architecturally. If you were to apply dependency inversion and cast CriticAgent to ChatAgent or to BaseAgent to abstract away the concrete inplementation, `run` will not be available any more and the CriticAgent won't be able to fulfil its purpose.

**Comment by Obs01ete** [comment]
Secondly, what do you think about this:
https://github.com/camel-ai/camel/pull/197#issuecomment-1620492500
It is composition (nesting in your terms). So what's wrong with composition?

**Review by Obs01ete — APPROVED** [review]
I think this is a good middle ground to resolve the inheritance inconsistencies.

**Pull request merged**
