### PR TITLE
feat: Add SchemaModel backend for unified schema-based chat completion

### PR DESCRIPTION
**Pull request by yiyiyi0817**
## Description

image

- [ ] I have raised an issue to propose this change ([required](https://github.com/camel-ai/camel/issues) for new features and bug fixes)

## Error Message

Traceback (most recent call last):
  File "/xxxx/camel/camel/examples/models/schema_model_example.py", line 71, in <module>
    user_msg = OpenAIMessage(
               ^^^^^^^^^^^^^^
  File "/sw/rl9g/python/3.11.0/rl9_gnu12.2.0/lib/python3.11/typing.py", line 1251, in __call__
    result = self.__origin__(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sw/rl9g/python/3.11.0/rl9_gnu12.2.0/lib/python3.11/typing.py", line 463, in __call__
    raise TypeError(f"Cannot instantiate {self!r}")
TypeError: Cannot instantiate typing.Union

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [x] Example (update in the folder of example)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by lightaime** [comment]
Thanks for the PR! I think it would be better to support structured output in the `step` function since users may want to get different structured outputs during the chat session at different steps. A related issue here: https://github.com/camel-ai/camel/issues/591

**Comment by Appointat** [comment]
@lightaime Hi, the original plan (after some discussions between us @raywhoelse @Wendong-Fan @Appointat  ) is that the structured output of the agent is determined during initialization of chatagent, which means that the structure will be fixed and unchangeable. However, based on your comments, I guess you want the step function to receive a schema parameter? Something like:  `step(self, messages, structured_schema)` ? If yes, we will modify the implementation. Thanks for your reply.

**Comment by lightaime** [comment]
Yes, I don’t think it would be fixed during initialization.

**Comment by Appointat** [comment]
@yiyiyi0817 I will reopen the pr, and add the description about the schema/structured output.

**Pull request closed without merging**
