### PR TITLE
docs：Add society doc

### LINKED ISSUE #772: [Feature Request] Documentation for `Roleplaying`
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Documentation for `Roleplaying`

### Solution

_No response_

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Asher-hss**
## Description

Describe your changes in detail.

## Motivation and Context

 `close #772 ` 

- [x] I have raised an issue to propose this change ([required](https://github.com/camel-ai/camel/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)
- [ ] Example (update in the folder of example)

## Implemented Tasks

- [ ] Subtask 1
- [ ] Subtask 2
- [ ] Subtask 3

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [ ] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by Wendong-Fan — COMMENTED** [review]
Thanks @Asher-hss !
I added one commit here https://github.com/camel-ai/camel/pull/818/commits/6933e48b7440dbe83dd15a20cbfae1024b410d0b

I feel the Init_chat Function and Step Function part is not necessary, WDY?

**Comment by Asher-hss** [comment]
> Thanks @Asher-hss ! I added one commit here [6933e48](https://github.com/camel-ai/camel/commit/6933e48b7440dbe83dd15a20cbfae1024b410d0b)
> 
> I feel the Init_chat Function and Step Function part is not necessary, WDY?

Thanks @Wendong-Fan, I think it depends on how we define this document. If it's intended for simple use, then the sections on the Init_chat function and Step function may not be necessary. However, if you want to make it clearer for users to understand what they need to do during ‘Get Started’, including those sections would be essential.

**Comment by Wendong-Fan** [comment]
> > Thanks @Asher-hss ! I added one commit here [6933e48](https://github.com/camel-ai/camel/commit/6933e48b7440dbe83dd15a20cbfae1024b410d0b)
> > I feel the Init_chat Function and Step Function part is not necessary, WDY?
> 
> Thanks @Wendong-Fan, I think it depends on how we define this document. If it's intended for simple use, then the sections on the Init_chat function and Step function may not be necessary. However, if you want to make it clearer for users to understand what they need to do during ‘Get Started’, including those sections would be essential.

@Asher-hss Init_chat Function and Step Function are not highly related to society part, it's more like a basic guidance about how to set up your chat agent, so I think we can remove this 2 functions as this part would be included in /Users/enrei/Desktop/camel_debug/camel/docs/agents/single_agent.md

**Review by Wendong-Fan — APPROVED** [review]
Thanks @Asher-hss ! I added one more commit here: https://github.com/camel-ai/camel/pull/818/commits/ef97d3a5947e5c5650a46a379c509a4efedb902c to remove some parts I think not necessary, please review it and let me know you have any suggestions

**Pull request merged**
