### PR TITLE
docs: o1datagen_sft_qwen_with_unsolth_upload_to_hf with CAMEL

### PR DESCRIPTION
**Pull request by zjrwtx**
…ing Qwen models with Unsloth

## Description

Describe your changes in detail.

## Motivation and Context

Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.
You can use the syntax `close #15213` if this solves the issue #15213

- [ ] I have raised an issue to propose this change ([required](https://github.com/camel-ai/camel/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [ ] Example (update in the folder of example)

## Implemented Tasks

- [ ] Subtask 1
- [ ] Subtask 2
- [ ] Subtask 3

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [ ] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by zjrwtx** [comment]
Since the pr for o1 data synthesis is still in the review stage, this cook is also in the draft stage

**Comment by zjrwtx** [comment]
colab link：https://colab.research.google.com/drive/1R3o7FcQQx77mskNf9czrJkAnzKruQhqb?usp=sharing

**Comment by AveryYay** [comment]
@zjrwtx Thank you for the cookbook! I think the code overall looks great! Maybe we can clean up the comments and explanation a little bit (@Wendong-Fan I'm not sure if that's what we want) ? 

Just a reminder, we might need to replace the git clone command to install camel package once the relevant PR is merged.

**Review by Wendong-Fan — COMMENTED** [review]
Thanks @zjrwtx ! please refer to https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md#contributing-to-the-cookbook-writing- and the cookbook template, add colab link, star the repo part etc.. into the cookbook, you also need to update `docs/index.rst` and `docs/README.md`

**Review by Wendong-Fan — COMMENTED** [review]
thanks @zjrwtx, added some comments into colab notebook

**Comment by zjrwtx** [comment]
> thanks @zjrwtx, added some comments into colab notebook
thanks @Wendong-Fan  , i already resolve all comment ，But I still need you to double check

**Comment by Asher-hss** [comment]
Thanks @zjrwtx added some comments into colab notebook

**Review by Wendong-Fan — APPROVED** [review]

**Pull request merged**
