### PR TITLE
Add `babyagi` into `agents`

### LINKED ISSUE #187: [Feature Request] OpenAI function call
See https://platform.openai.com/docs/guides/gpt/function-calling.

### PR DESCRIPTION
**Pull request by hychen-naza**
## Description

Add `babyagi code` under camel agents, and put its its `example code` and `testing code` in corresponding folders. It's my first commit, and I appreciate your feedback and suggestions to make my code better align with yours. 

Babyagi Agent works by running an infinite loop that does the following steps:
1, Pulls the first task from the task list.
2, Sends the task to the execution agent, which uses OpenAI's API to complete the task based on the context.
3, Enriches the result and stores it in [Chroma](https://docs.trychroma.com/).
4, Creates new tasks and reprioritizes the task list based on the objective and the result of the previous task.

Compared to role-play, which has AI user and AI assistant, Babyagi Agent gives itself instructions through task creation and solve solutions by task execution.

## Motivation and Context

Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.
close #187
- [x] I have raised an issue to propose this change ([required](https://github.com/camel-ai/camel/issues/186) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [x] Example (update in the folder of example)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by hychen-naza** [comment]
Emmm, it seems like most checks are failed. Still working on it.

**Comment by lightaime** [comment]
Thanks, @hychen-naza for the PR. No worries. We will take a look at it soon.

**Comment by Obs01ete** [comment]
Thanks for the MR. For those who is not familiar with this paper, please put 2-3 sentenses of description of what BabyAGI is and how it is different from RolePlaying.

**Comment by lightaime** [comment]
> Thanks for the MR. For those who is not familiar with this paper, please put 2-3 sentenses of description of what BabyAGI is and how it is different from RolePlaying.

Here is a writeup from the authors: https://yoheinakajima.com/task-driven-autonomous-agent-utilizing-gpt-4-pinecone-and-langchain-for-diverse-applications/.

**Comment by hychen-naza** [comment]
Hi, thanks for your review and comments.

Babyagi Agent is explained at the description of this PR. Also, I have updated the Babyagi Agent to make it inherit from Base Agent, according to https://github.com/camel-ai/camel/pull/198#issue-1786192208.

**Comment by Obs01ete** [comment]
Thanks for the overview of BabyAGI in the description. This is really helpful.
Regarding dependencies, you need to add them to pyproject.toml poetry section. 

@lightaime what about the binary blobs. We should not add them to the repo.

@hychen-naza Is there a way to not add parquet and other binary stuff to the repo: create them or download?

**Comment by Benjamin-eecs** [comment]
> 2, Doc check failures: I can build the documentations successfully in my local (following [`llm_agents_hy`/docs](https://github.com/camel-ai/camel/tree/llm_agents_hy/docs?rgh-link-date=2023-07-04T04%3A25%3A37Z)), but I have no idea why it fails when merging to master.

@lightaime @Obs01ete Mind taking a look to see what's wrong, the docs github action failed is really weird to me

**Comment by hychen-naza** [comment]
Thanks guys. I created a new branch and PR for debugging, #210
It went through the doc check and dependency checks, even though it failed in mypy check. I will look into that tomorrow and move everything into that branch, and may close this PR later.
We are all good for now.

**Pull request closed without merging**
