### PR TITLE
add web search

### PR DESCRIPTION
**Pull request by zhiyu-01**
## Description

Search web for information.
When agent ask a question, google search can provide a list of urls which relative with the question, then using requests to get
each url and extract text. Split the text to small chunks and feed to chatgpt to get answer.

Notice: these functions require google api key you can find here https://developers.google.com/custom-search/v1/overview,
and search engine id you can find here https://cse.google.com/cse/all.

So, can anyone add these two key into the github actions, my pr need them to pass the test, thanks!
They look like this:

    GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
    SEARCH_ENGINE_ID = os.getenv("SEARCH_ENGINE_ID")

## Motivation and Context

Why is this change required? What problem does it solve?
Give the agent ability to search internet.

- [ ] I have raised an issue to propose this change ([required](https://github.com/camel-ai/camel/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [ ] Example (update in the folder of example)

## Implemented Tasks

- [ ] Subtask 1
- [ ] Subtask 2
- [ ] Subtask 3

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [x] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Benjamin-eecs** [comment]
I think this pr is awesome! Any reason why you close this?

**Comment by MorphlingEd** [comment]
I have just noticed this new PR but before reviewing I think it would be better for you to do local cheks first before committing and pushing. It sends quite a lot of emails into my inboxes... And may I ask why you close this?

**Comment by zhiyu-01** [comment]
> I think this pr is awesome! Any reason why you close this?

This pr is submmit from my fork, it can't use sercet api key, so I opened another pr #274 from a branch.

**Comment by zhiyu-01** [comment]
> I have just noticed this new PR but before reviewing I think it would be better for you to do local cheks first before committing and pushing. It sends quite a lot of emails into my inboxes... And may I ask why you close this?

sorry about that, i met a wierd error. Everything goes well in my laptap, but get wrong in github, it said i give a 'function' type, but expect 'Callable' type, i dont know why, so i try to delete some functions.

**Comment by zhiyu-01** [comment]
> I have just noticed this new PR but before reviewing I think it would be better for you to do local cheks first before committing and pushing. It sends quite a lot of emails into my inboxes... And may I ask why you close this?

This pr is submmit from my fork, it can't use sercet api key, so I opened another pr https://github.com/camel-ai/camel/pull/274 from a branch.

**Pull request closed without merging**
