### PR TITLE
docs: Added discord bot with agentic RAG supports local model

### PR DESCRIPTION
**Pull request by AveryYay**
## Description

Added discord bot with agentic RAG which supports local model deployment.
Google colab link: https://colab.research.google.com/drive/1Knq9y5TQ6oeKumWdg9MlWT9gfSsTlqCZ#scrollTo=DCiF-4DQAZIS

## Motivation and Context

Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.
You can use the syntax `close #15213` if this solves the issue #15213

- [ ] I have raised an issue to propose this change ([required](https://github.com/camel-ai/camel/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [ ] Example (update in the folder of example)

## Implemented Tasks

- [ ] Subtask 1
- [ ] Subtask 2
- [ ] Subtask 3

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [ ] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by Wendong-Fan — COMMENTED** [review]
Thanks @AveryYay ! please pay attentation to the pr naming, refer to https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md#board-item-create-workflow-%EF%B8%8F

Screenshot 2024-12-16 at 13 28 24

could you based on our new discord bot cookbook here https://docs.camel-ai.org/cookbooks/customer_service_Discord_bot_using_SambaNova_with_agentic_RAG.html to update your current cookbook? there's some changes like agent memory management and so on

**Comment by AveryYay** [comment]
> Thanks @AveryYay ! please pay attentation to the pr naming, refer to https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md#board-item-create-workflow-%EF%B8%8F
> 
> Screenshot 2024-12-16 at 13 28 24
> could you based on our new discord bot cookbook here https://docs.camel-ai.org/cookbooks/customer_service_Discord_bot_using_SambaNova_with_agentic_RAG.html to update your current cookbook? there's some changes like agent memory management and so on

Thanks for the feed back! @Wendong-Fan I have updated the cookbook, please check!

**Review by Wendong-Fan — COMMENTED** [review]
hey @AveryYay , I think we can directly switch the model setting from Qwen Cloud to Ollama, using Qwen 2.5 72B and Qwen 2.5 Coder 32B instead of llama based on the cookbook here: https://colab.research.google.com/drive/1j7U-QN4MLckJoaUoprODGtD-jjPIQkLc?usp=sharing, we can leverage external knowledge from this reference: https://venturebeat.com/ai/alibaba-releases-qwen-with-questions-an-open-reasoning-model-that-beats-o1-preview/

**Review by Wendong-Fan — COMMENTED** [review]
Thanks @AveryYay!

**Pull request merged**
